### ISSUE TITLE
How to get the result pictures and save them, rather than display on the screen.

### ISSUE THREAD

**Issue by Kimsure** [kuixu/kitti_object_vis#42]
What you have done is very impressive.But my linux server doesn`t have GUI interface, I want to know how to get the pictures of detective result, rather than display on the screen.
Thanks a lot!

**Comment by kuixu** [comment]
Hi @Kimsure, have you solved this problem? it's possible to save into an image rather than display. 

- For `cv2` window, you could replace `cv2.imshow` with `cv2.imwrite('/your/path/name.png', image)`. 
- For `mlab` window, you could replace `mlab.show(1)` with `mlab.savefig('/your/path/name.png')`.

**Comment by Kimsure** [comment]
yeah I have solved this problem. Thank you very much anyway.
